package com.geoattendance.api;
import com.geoattendance.domain.*; import com.geoattendance.repository.*; import java.time.Instant; import java.util.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api") public class MobileAttendanceController {
 private final StudentRepository students; private final TeacherRepository teachers; private final ClassSessionRepository sessions; private final AttendanceRecordRepository attendance; private final RoomRepository rooms; private final BeaconRepository beacons; private final FloorRepository floors; private final RoomBeaconRepository roomBeacons;
 public MobileAttendanceController(StudentRepository students,TeacherRepository teachers,ClassSessionRepository sessions,AttendanceRecordRepository attendance,RoomRepository rooms,BeaconRepository beacons,FloorRepository floors,RoomBeaconRepository roomBeacons){this.students=students;this.teachers=teachers;this.sessions=sessions;this.attendance=attendance;this.rooms=rooms;this.beacons=beacons;this.floors=floors;this.roomBeacons=roomBeacons;}
 @PostMapping("/login") Map<String,Object> login(@RequestBody Map<String,Object>b){Teacher t=teachers.findByEmail(text(b,"email")).orElse(null);if(t==null||t.getPassword()==null||!t.getPassword().equals(text(b,"password")))return fail("Invalid credentials");return ok(Map.of("access_token","local-"+t.getId(),"user",Map.of("id",t.getId(),"name",t.getName(),"erp_id",t.getErpId())));}
 @PostMapping("/markAttendance") ResponseEntity<Map<String,Object>> mark(@RequestBody Map<String,Object>b){Student s=students.findByUid(text(b,"uid")).orElse(null);Long sessionId=number(b,"class_id");if(s==null||sessionId==null)return ResponseEntity.badRequest().body(fail("Student or class session not found"));ClassSession session=sessions.findById(sessionId).orElse(null);if(session==null)return ResponseEntity.badRequest().body(fail("Class session not found"));if(attendance.existsByClassSessionIdAndStudentId(sessionId,s.getId()))return ResponseEntity.ok(fail("Attendance already marked"));AttendanceRecord r=new AttendanceRecord();r.setStudent(s);r.setClassSession(session);r.setMarkedAt(Instant.now());r.setStatus(AttendanceStatus.PRESENT);r.setFaceVerified(true);r.setGeoVerified(true);r.setBeaconVerified(true);r.setDetectedRoom(session.getTimetable().getRoom());attendance.save(r);return ResponseEntity.ok(ok(Map.of("attendance_id",r.getId())));}
 @PostMapping("/beacon/assign") Map<String,Object> assign(@RequestBody Map<String,Object>b){Long roomId=number(b,"roomId");Long floorId=number(b,"floorId");if(roomId==null||floorId==null)return fail("roomId and floorId are required");Room room=rooms.findById(roomId).orElseThrow();Beacon beacon=beacons.findByLabel(text(b,"beaconId")).orElseGet(()->{Beacon x=new Beacon();x.setLabel(text(b,"beaconId"));x.setFloor(floors.findById(floorId).orElseThrow());x.setUuid(text(b,"beaconId"));x.setMajorValue(0);x.setMinorValue(0);return beacons.save(x);});RoomBeacon rb=roomBeacons.findFirstByRoomId(roomId).orElseGet(RoomBeacon::new);rb.setRoom(room);rb.setBeacon(beacon);roomBeacons.save(rb);return ok(Map.of("beaconId",beacon.getLabel()));}
 @GetMapping("/beacon/get") Map<String,Object> beacon(@RequestParam Long roomId){return roomBeacons.findFirstByRoomId(roomId).map(x->ok(Map.of("beaconId",x.getBeacon().getLabel()))).orElseGet(()->fail("No beacon assigned"));}
 private String text(Map<String,Object>b,String k){Object v=b.get(k);return v==null?null:v.toString();} private Long number(Map<String,Object>b,String k){try{return Long.valueOf(text(b,k));}catch(Exception e){return null;}} private Map<String,Object>ok(Object d){return Map.of("success",true,"message","Success","data",d);}private Map<String,Object>fail(String m){return Map.of("success",false,"message",m);}
}
