package com.geoattendance.api;

import com.geoattendance.domain.*; import com.geoattendance.repository.*; import java.time.LocalDate; import java.util.*;
import org.springframework.http.*; import org.springframework.web.bind.annotation.*;

/** Preserves the JSON shapes already used by the Flutter mobile application. */
@RestController @RequestMapping("/api")
public class MobileCompatibilityController {
 private final StudentRepository students; private final BlockRepository blocks; private final FloorRepository floors; private final RoomRepository rooms;
 public MobileCompatibilityController(StudentRepository students, BlockRepository blocks, FloorRepository floors, RoomRepository rooms) {this.students=students;this.blocks=blocks;this.floors=floors;this.rooms=rooms;}
 @GetMapping("/students") Map<String,Object> students(){ return ok(toList(students.findAll(),this::student)); }
 @PostMapping("/students") ResponseEntity<Map<String,Object>> create(@RequestBody Map<String,Object> b){ if(students.findByUid(str(b,"student_uid")).isPresent()) return ResponseEntity.status(409).body(fail("Student UID already exists")); Student s=new Student(); s.setUid(str(b,"student_uid"));s.setName(str(b,"name"));s.setPhoneNumber(str(b,"mobileno"));s.setEmail(str(b,"emailid"));s.setFatherName(str(b,"fathername"));s.setMotherName(str(b,"mothername"));s.setAddress(str(b,"address"));s.setPassword(str(b,"password"));s.setStatus("inactive".equalsIgnoreCase(str(b,"status"))?PersonStatus.INACTIVE:PersonStatus.ACTIVE); try{s.setGender(Gender.valueOf(str(b,"gender").toUpperCase().replace(" ","_")));}catch(Exception ignored){} try{s.setDob(LocalDate.parse(str(b,"dob")));}catch(Exception ignored){} students.save(s); return ResponseEntity.status(201).body(ok(student(s))); }
 @GetMapping("/studentlogin") Map<String,Object> studentLogin(@RequestParam String id,@RequestParam String password){ Student s=students.findByUid(id).orElse(null); if(s==null||s.getPassword()==null||!s.getPassword().equals(password)) return fail("Invalid credentials"); return ok(student(s)); }
 @GetMapping("/getBlocks") Map<String,Object> getBlocks(){return ok(toList(blocks.findAll(),b->Map.of("id",b.getId(),"name",b.getName())));}
 @GetMapping("/getFloors") Map<String,Object> getFloors(@RequestParam("blockid") Long blockId){return ok(toList(floors.findByBlockId(blockId),f->Map.of("id",f.getId(),"name",f.getName())));}
 @GetMapping("/flatplotstatus") Map<String,Object> getRooms(@RequestParam("blockid") Long blockId,@RequestParam("floorid") Long floorId){return ok(toList(rooms.findByFloorId(floorId),this::room));}
 @GetMapping("/flatplots/{id}") Map<String,Object> getRoom(@PathVariable Long id){return ok(room(rooms.findById(id).orElseThrow()));}
 @PostMapping("/flatplots/{id}") Map<String,Object> updateRoom(@PathVariable Long id,@RequestBody Map<String,Object> b){ Room r=rooms.findById(id).orElseThrow(); setCoordinates(r,b); rooms.save(r); return ok(room(r)); }
 private void setCoordinates(Room r,Map<String,Object>b){ if(b.containsKey("geo_north")){r.setNorthLongitude(num(b,"geo_north"));r.setNorthLatitude(num(b,"geo_north_lat"));} if(b.containsKey("geo_south")){r.setSouthLongitude(num(b,"geo_south"));r.setSouthLatitude(num(b,"geo_south_lat"));} if(b.containsKey("geo_east")){r.setEastLongitude(num(b,"geo_east"));r.setEastLatitude(num(b,"geo_east_lat"));} if(b.containsKey("geo_west")){r.setWestLongitude(num(b,"geo_west"));r.setWestLatitude(num(b,"geo_west_lat"));} }
 private Map<String,Object> student(Student s){Map<String,Object>m=new LinkedHashMap<>();m.put("id",s.getId());m.put("name",s.getName());m.put("student_uid",s.getUid());m.put("mobileno",s.getPhoneNumber());m.put("emailid",s.getEmail());m.put("gender",s.getGender()==null?null:s.getGender().name());m.put("address",s.getAddress());return m;}
 private Map<String,Object> room(Room r){Map<String,Object>m=new LinkedHashMap<>();m.put("id",r.getId());m.put("name",r.getName());m.put("idname",r.getRoomCode());m.put("flatno",r.getRoomCode());m.put("geo_north",r.getNorthLongitude());m.put("geo_north_lat",r.getNorthLatitude());m.put("geo_south",r.getSouthLongitude());m.put("geo_south_lat",r.getSouthLatitude());m.put("geo_east",r.getEastLongitude());m.put("geo_east_lat",r.getEastLatitude());m.put("geo_west",r.getWestLongitude());m.put("geo_west_lat",r.getWestLatitude());return m;}
 private Map<String,Object> ok(Object data){return Map.of("success",true,"data",data,"message","Success");} private Map<String,Object> fail(String message){return Map.of("success",false,"message",message);} private String str(Map<String,Object>b,String k){Object v=b.get(k);return v==null?null:v.toString();} private Double num(Map<String,Object>b,String k){try{return Double.valueOf(str(b,k));}catch(Exception e){return null;}} private <T> List<Object> toList(Iterable<T> it,java.util.function.Function<T,Object> mapper){List<Object> out=new ArrayList<>();it.forEach(x->out.add(mapper.apply(x)));return out;}
}
